let divBox = document.getElementById("divv");
divBox.style.backgroundColor = "yellow";
divBox.style.color = "blue";
divBox.style.padding = "10px";
divBox.style.fontSize = "18px";
divBox.style.fontWeight = "bold";
divBox.style.margin = "20px";
divBox.style.width = "300px";
divBox.style.height = "200px";